### ISSUE TITLE
ChromeDriverManager().install() --> no such driver by url http://chromedriver.storage.googleapis.com/LATEST_RELEASE_117.0.5938

### ISSUE THREAD

**Issue by avivajpeyi** [alexsomai/stackoverflow-fanatic-badge#22]
Is anyone else getting this error? Running on py3.8

```
>>> from selenium import webdriver
>>> from webdriver_manager.chrome import ChromeDriverManager
>>> driver = webdriver.Chrome(ChromeDriverManager().install())
 
[WDM] - Current google-chrome version is 117.0.5938
[WDM] - Get LATEST driver version for 117.0.5938
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/avaj040/.local/lib/python3.8/site-packages/webdriver_manager/chrome.py", line 31, in install
    driver_path = self._get_driver_path(self.driver)
  File "/home/avaj040/.local/lib/python3.8/site-packages/webdriver_manager/manager.py", line 22, in _get_driver_path
    driver_version = driver.get_version()
  File "/home/avaj040/.local/lib/python3.8/site-packages/webdriver_manager/driver.py", line 40, in get_version
    return self.get_latest_release_version()
  File "/home/avaj040/.local/lib/python3.8/site-packages/webdriver_manager/driver.py", line 64, in get_latest_release_version
    validate_response(resp)
  File "/home/avaj040/.local/lib/python3.8/site-packages/webdriver_manager/utils.py", line 79, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url http://chromedriver.storage.googleapis.com/LATEST_RELEASE_117.0.5938
```

**Comment by avivajpeyi** [comment]
Seems like the following change allows us to run the install
https://github.com/SergeyPirogov/webdriver_manager/issues/536#issuecomment-1641806492

```
ChromeDriverManager(version="114.0.5735.90").install()
```
